#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

set -o vi
alias ls='ls --color=auto'
alias battery='cat /sys/class/power_supply/BAT1/capacity'

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
alias start='~/dotfiles/startx.sh'
