#!/bin/sh

usermodmap=$HOME/.xmodmap
sysmodmap=/etc/X11/xinit/.Xmodmap
userresources=$HOME/.Xresources

# merge in defaults and keymaps

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

xsetroot -cursor_name left_ptr
xset r rate 200 60

# Background
feh --bg-fill ~/dotfiles/wallpaper.jpg
# Status bar loop
while true; do
    xsetroot -name "date: $( date +"%F" ) < time: $( date +"%R") < bat: $( cat /sys/class/power_supply/BAT1/capacity)%"
    sleep 1m
done &

[[ -f "$userresources" ]] && xrdb -merge "$userresources" &
	xrandr --dpi 115

# Window Manager
exec dwm
